### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [SethTeck/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by SethTeck** [comment]
Thanks for the tip Ken. I added a line of code to the head of application.html.erb
Now things are looking better on mobile. I noticed when I highlight text on my iPhone it's not red. Not huge deal I suppose, but I'm curious if you knew the reason for that.

**Comment by kenmazaika** [comment]
Thumbs up :+1: 

I believe on the iPhone, the browser doesn't allow customizing this, because the "copy & paste" magic is universal across all apps, and it's always blue.

Keep up the good work coding, Seth! :)
